# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Gender', models.BooleanField(default=False)),
                ('Age', models.IntegerField(default=18)),
                ('Memo', models.TextField(default='Memo')),
                ('CreateDate', models.DateField(default='2016-10-01')),
                ('CreateTime', models.DateTimeField(default='2016-10-01 10:10:10')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApps.UserType'),
        ),
    ]
